name: debug cloudflared
on:
  workflow_dispatch:
jobs:
  ssh_command:
    if: github.event.pull_request.merged == true
    name: Run SSH command
    runs-on: ubuntu-latest
    steps:
      - name: Connect and run command on remote server
        uses: and-fm/cloudflared-ssh-action@v3
        with:
          host: ${{ secrets.SSH_HOST_1 }}
          username: ${{ secrets.SSH_USER }}
          private_key_filename: id_ed25519
          private_key_value: ${{ secrets.SSH_PRIVATE_KEY }}
          service_token_id: ${{ secrets.CLOUDFLARED_TOKEN_ID }}
          service_token_secret: ${{ secrets.CLOUDFLARED_TOKEN_SECRET }}
          commands: uname -a
